# Generated by Django 5.0.6 on 2024-06-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_enquiry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('cars', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Market Appraisals',
            },
        ),
    ]
