# Generated by Django 5.0.6 on 2024-06-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_soldlisting_listing_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
