# Generated by Django 5.0.6 on 2024-06-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_listing_sold_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'Listings'},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Area',
            new_name='area',
        ),
    ]
