# Generated by Django 5.0.6 on 2024-07-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldlisting',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldlisting',
            name='lot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
